# Set the base image to nginx:1.15.8
   FROM nginx:1.15.8

# File Author / Maintainer
  MAINTAINER shankar

# Copy fruit.json file from the static directory
  ADD /static/fruit.json /usr/share/nginx/html/

# Copy a configuration file from the current directory
  ADD nginx.conf /etc/nginx/

# Expose ports
  EXPOSE 80

# Set the default command to execute
# when creating a new container
  CMD ["nginx", "-g", "daemon off;"]